namespace elv_version{

// DO NOT EDIT!
// file generated by scripts/generate-bitcode-version-info.sh

class ELV_VERSION {
public:
	static const int64_t commit_date;
	static const char* revision;
	static const char* branch;
	static const char* version;
};

const int64_t ELV_VERSION::commit_date = 1589542620;
const char* ELV_VERSION::revision      = "019aec14b47f0f04da78142c4159a782e51e95e0";
const char* ELV_VERSION::branch        = "search.v2.post";
const char* ELV_VERSION::version       = "";

}; //namespace elv_version
